#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${POSTGRES_GENERAL_USERNAME} WITH SUPERUSER PASSWORD '${POSTGRES_GENERAL_PASSWORD}';
    CREATE DATABASE ${POSTGRES_GENERAL_DATABASE};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_GENERAL_DATABASE} TO ${POSTGRES_GENERAL_USERNAME};
EOSQL
